# docker-compose.yml
version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: writerpanel
    ports:
      - "3306:3306"
